@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
<<<<<<< HEAD
REM Generated by Vivado on Tue Apr 06 18:44:56 -0300 2021
=======
REM Generated by Vivado on Mon Apr 12 19:08:47 -0300 2021
>>>>>>> rollback
REM SW Build 2902540 on Wed May 27 19:54:49 MDT 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim tb_pipeline_behav -key {Behavioral:sim_1:Functional:tb_pipeline} -tclbatch tb_pipeline.tcl -view T:/Repositorios/arqui2020/tp4-MIPS/tb_mips_np_behav.wcfg -log simulate.log"
call xsim  tb_pipeline_behav -key {Behavioral:sim_1:Functional:tb_pipeline} -tclbatch tb_pipeline.tcl -view T:/Repositorios/arqui2020/tp4-MIPS/tb_mips_np_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
