# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/contraints.xdc

# IP: ip/clock/clock.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clock || ORIG_REF_NAME==clock} -quiet] -quiet

# XDC: ip/clock/clock_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clock || ORIG_REF_NAME==clock} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/clock/clock.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clock || ORIG_REF_NAME==clock} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/clock/clock_ooc.xdc
